[listener]
;host=192.168.0.100
port=8082
minThreads=4
maxThreads=100
cleanupInterval=60000
readTimeout=60000
maxRequestSize=16000
maxMultiPartSize=10000000

[logging]
uselogfile=0
fileName=../logs/qtwebserver.log
minLevel=1
bufferSize=100
maxSize=1000000
maxBackups=2
timestampFormat=dd.MM.yyyy hh:mm:ss.zzz
msgFormat={timestamp} {typeNr} {type} {thread} {msg}
; QT5 supports: msgFormat={timestamp} {typeNr} {type} {thread} {msg}\n  in {file} line {line} function {function}

[docroot]
path=dist ;frontend path
encoding=UTF-8
maxAge=60000
cacheTime=60000
cacheSize=1000000
maxCachedFileSize=65536

[api]
apipath=/matr/
suites=suites
exchange=exchange
products=products    

[publications]
path=publications

[auth]
enabled=true ;auth&sessions support
users=users  ;path to file with users/passwords in format "login:pwd\nlogin2:pwd2\n....." 
cookieName=session ;session cookie name
cookiePath=/ ;
;cookieComment = abc
;cookieDomain = domain.com
;expirationTime = 3600000 ; session expiration time in millis, 3600s=1h by default

;custom http headers
[http-headers]
header1="Access-Control-Allow-Origin:*"
header2="Access-Control-Allow-Methods:GET, POST, OPTIONS"
header3="Access-Control-Allow-Headers:Content-Type, Authorization"

;external AYatzk service params
[remote-service]
enabled=true
timeout=10000
;url=http://192.168.32.111:7239
url=http://localhost:7239
;login=Administrator
;password=
database=MATRYOSHKA

[http-headers]
header1="Access-Control-Allow-Origin:http://localhost:5175"
header2="Access-Control-Allow-Methods:GET, POST, OPTIONS"
header3="Access-Control-Allow-Headers:Content-Type, Authorization"
header4="Access-Control-Allow-Credentials:true"

[external-apps]
grabber.name="Дозор-ТСВ"
grabber.command="soft/grabber"
grabber.dataPath="soft/grabber_data"
armtsv.name="АРМ-ТСВ"
armtsv.command="soft/armtsv"
armtsv.dataPath="soft/armtsv_data"